# Pipeline: From Idea to ZIP (Marketing-First)
#
# Marketing-focused version using CodeSkeletonMarketingAgent by default.
# Optimized for creating marketing landing pages with hero, features, testimonials.
#
# Usage:
#   python cli.py --pipeline pipeline/gallery/idea-to-zip/pipeline-marketing-first.yaml \
#     --mem 'product_idea="Coffee shop" brand="BlueBean" primary_color="#0ea5e9" tone="minimal" font_family="Inter"' \
#     --save-artifacts --output human

stages:
  - name: Product Definition
    agent: RequirementsDraftingAgent
    advisor: RequirementsAdvisor
    output: docs/product_definition.md
    min_score: 0.75
    description: "Define the product from the idea"
    category: requirements
    task: |
      Create comprehensive PRD for: {{ product_idea }}
      Brand: {{ brand | default("Default") }}
      Design tone: {{ tone | default("professional") }}
      Primary color: {{ primary_color | default("#007bff") }}
      Include: goals, personas, features, marketing messaging, CTA strategy

  - name: Code Skeleton (Marketing)
    agent: CodeSkeletonMarketingAgent
    advisor: CodeReviewAdvisor
    input: docs/product_definition.md
    output: src/index.html
    min_score: 0.70
    description: "Generate marketing HTML/CSS with hero, features, testimonials"
    category: codegen
    task: |
      Generate marketing landing page for: {{ product_idea }}
      Brand: {{ brand | default("Default") }}
      Primary color: {{ primary_color | default("#007bff") }}
      Tone: {{ tone | default("professional") }}
      Font: {{ font_family | default("system-ui") }}
      Include:
      - Hero section with headline and CTA button
      - Features section (3 columns)
      - Testimonials section
      - Footer with branding
      - Responsive design (mobile-first)
      - Modern CSS (flexbox/grid)

  - name: Static Lint
    agent: StaticLinterAgent
    advisor: CodeReviewAdvisor
    input: src/index.html
    output: reports/lint_report.md
    min_score: 0.70
    description: "Lint the generated marketing code"
    category: validation

  - name: Accessibility Audit
    agent: AccessibilityAuditAgent
    advisor: CodeReviewAdvisor
    input: src/index.html
    output: reports/a11y_report.md
    min_score: 0.70
    description: "Check accessibility compliance for marketing page"
    category: validation

  - name: Screenshot
    agent: ScreenshotAgent
    advisor: CodeReviewAdvisor
    input: src/index.html
    output: screenshots/preview.png
    min_score: 0.50
    description: "Generate screenshot preview of marketing page"
    category: validation
    task: |
      Generate screenshot of: src/index.html
      Dimensions: 1920x1080
      Full page screenshot

  - name: Documentation
    agent: RequirementsDraftingAgent
    advisor: RequirementsAdvisor
    input: docs/product_definition.md
    output: README.md
    min_score: 0.70
    description: "Generate marketing-focused project README"
    category: documentation
    task: |
      Create marketing-focused README for: {{ product_idea }}
      Include:
      - Project description
      - Design system (brand: {{ brand }}, color: {{ primary_color }}, tone: {{ tone }})
      - Marketing messaging
      - Setup instructions
      - Usage examples
      - Screenshots section
      - License

  - name: Package ZIP
    agent: ZipPackagerAgent
    advisor: CodeReviewAdvisor
    input:
      - src/index.html
      - README.md
      - reports/lint_report.md
      - reports/a11y_report.md
      - screenshots/preview.png
    output: dist/package.zip
    min_score: 0.50
    description: "Create distributable ZIP package with marketing assets"
    category: packaging

policy:
  version: 1
  thresholds:
    overall: 0.70
    requirements: 0.75
    codegen: 0.70
    validation: 0.70
    documentation: 0.70
    packaging: 0.50
  timeouts:
    default: 300
    requirements: 60
    codegen: 120
    validation: 120
    documentation: 60
    packaging: 30
  retries:
    default: 1
    codegen: 2
    validation: 1
  advisors:
    council:
      - name: RequirementsAdvisor
        weight: 1.0
      - name: CodeReviewAdvisor
        weight: 1.5
  budget:
    max_bytes: 10_000_000
    max_stages: 10
