"""Generator: Create new pipeline scaffold."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Optional


def generate_pipeline_scaffold(
    name: str,
    output_dir: str = ".",
    preset: Optional[str] = None,
) -> None:
    """
    Generate a new pipeline scaffold.

    Args:
        name: Pipeline name (e.g., "my-project")
        output_dir: Output directory
        preset: Optional preset name (mvp-fast, production, research)
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    pipeline_file = out / f"pipeline/{name}.yaml"
    pipeline_file.parent.mkdir(parents=True, exist_ok=True)

    # Generate pipeline YAML
    pipeline_content = f"""# Pipeline: {name}
# Auto-generated by multiagent new

project_mode: {"mvp-fast" if preset == "mvp-fast" else "production"}

policy:
  version: 1
  score_thresholds:
    requirements: {"0.8" if preset == "mvp-fast" else "0.85"}
    codegen: {"0.85" if preset == "mvp-fast" else "0.9"}
  retries:
    requirements: {"0" if preset == "mvp-fast" else "1"}
    codegen: {"1" if preset == "mvp-fast" else "2"}
  timeouts:
    requirements: 30
    codegen: 60
  budget:
    max_runtime_sec: 600
    max_stages: 10
    max_artifacts_bytes: 50000000

stages:
  - name: requirements
    category: requirements
    agent: RequirementsAgent
    advisor: RequirementsAdvisor
    task: "Define requirements for {{ product_idea }}"
    output: docs/requirements.md
    min_score: {"0.8" if preset == "mvp-fast" else "0.85"}

  - name: code_skeleton
    category: codegen
    agent: CodeSkeletonAgent
    advisor: CodeReviewAdvisor
    depends_on: [requirements]
    task: "Generate code skeleton"
    output: src/generated_code.py
    min_score: {"0.85" if preset == "mvp-fast" else "0.9"}

dependencies:
  code_skeleton: [requirements]
"""

    pipeline_file.write_text(pipeline_content, encoding="utf-8")

    # Generate README
    readme_file = out / f"{name}_README.md"
    readme_content = f"""# {name} Pipeline

This pipeline was generated by `multiagent new`.

## Quick Start

```bash
# Run pipeline
python cli.py --pipeline pipeline/{name}.yaml --output human --save-artifacts

# With preset
python cli.py --pipeline pipeline/{name}.yaml --preset {preset or "mvp-fast"}

# Dry-run
python cli.py --pipeline pipeline/{name}.yaml --dry-run --export-graph out/{name}.dot
```

## Stages

1. **requirements** - Define project requirements
2. **code_skeleton** - Generate initial code structure

## Customization

Edit `pipeline/{name}.yaml` to:
- Add more stages
- Adjust score thresholds
- Configure advisors
- Set budget limits

See [docs/INDEX.md](../docs/INDEX.md) for complete documentation.
"""

    readme_file.write_text(readme_content, encoding="utf-8")

    print("[OK] Generated pipeline scaffold:")
    print(f"   - Pipeline: {pipeline_file}")
    print(f"   - README: {readme_file}")
    print("\nNext steps:")
    print(f"   python cli.py --pipeline {pipeline_file} --dry-run")


def main() -> int:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Generate new pipeline scaffold",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  multiagent new my-project
  multiagent new my-project --preset mvp-fast
  multiagent new my-project --preset production --out ./projects
        """,
    )
    parser.add_argument("name", help="Pipeline name")
    parser.add_argument(
        "--preset",
        choices=["mvp-fast", "production", "research"],
        help="Use preset configuration",
    )
    parser.add_argument(
        "--out",
        type=str,
        default=".",
        help="Output directory (default: current directory)",
    )

    args = parser.parse_args()

    try:
        generate_pipeline_scaffold(
            name=args.name,
            output_dir=args.out,
            preset=args.preset,
        )
        return 0
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
