# Auto-generated by multi-agent pipeline. Edit with care.

"""
Marketing Template Code Skeleton Agent.

Generates HTML/CSS with marketing-focused structure:
- Hero section with CTA
- Features section
- Testimonials
- Footer with branding
"""

from pathlib import Path
from typing import Any

from src.core.base import BaseFunctionalAgent
from src.core.types import AgentMetadata, AgentOutput, Artifact


class CodeSkeletonMarketingAgent(BaseFunctionalAgent):
    """
    Generates marketing-focused HTML/CSS skeleton.

    Template includes: hero, features, testimonials, CTA sections.
    Uses design variables: brand, primary_color, tone, font_family.
    """

    def process(self, context: dict[str, Any]) -> dict[str, Any]:
        """
        Generate marketing HTML/CSS skeleton.

        Expected context:
            - task: Product idea/description
            - brand: Brand name
            - primary_color: Hex color (e.g., "#0ea5e9")
            - tone: Design tone (minimal, professional, playful)
            - font_family: Font name (e.g., "Inter")
        """
        task = context.get("task", "Marketing landing page")
        brand = context.get("brand", "Brand")
        primary_color = context.get("primary_color", "#007bff")
        tone = context.get("tone", "professional")
        font_family = context.get("font_family", "system-ui")

        # Generate HTML with marketing template
        html_content = self._generate_marketing_html(task, brand, primary_color, tone, font_family)

        # Output directory
        run_id = context.get("run_id", "latest")
        output_dir = Path("out") / run_id / "code_skeleton"
        output_dir.mkdir(parents=True, exist_ok=True)

        html_path = output_dir / "index.html"
        html_path.write_text(html_content, encoding="utf-8")

        content = f"""# Marketing Landing Page Generated

**HTML File**: `{html_path.relative_to(Path.cwd())}`
**Brand**: {brand}
**Primary Color**: {primary_color}
**Tone**: {tone}
**Font**: {font_family}

## Structure

- Hero section with headline and CTA
- Features section (3 columns)
- Testimonials section
- Footer with branding

## Design Variables Applied

- Primary color: {primary_color}
- Font family: {font_family}
- Tone: {tone}

## Usage

Open `{html_path.name}` in a browser to view the marketing landing page.
"""

        artifacts = [
            Artifact(
                name="index.html",
                type="text",  # HTML is text content
                content=html_content,
                description="Marketing landing page HTML",
            )
        ]

        metadata = AgentMetadata(
            agent_name="CodeSkeletonMarketingAgent",
            stage="codegen",
            input_summary=f"Marketing page for {brand}",
        )

        return AgentOutput(content=content, artifacts=artifacts, metadata=metadata)

    def _generate_marketing_html(
        self, task: str, brand: str, primary_color: str, tone: str, font_family: str
    ) -> str:
        """Generate marketing HTML template."""

        # Adjust colors based on tone
        if tone == "minimal":
            bg_color = "#ffffff"
            text_color = "#1a1a1a"
            secondary_color = "#f5f5f5"
        elif tone == "playful":
            bg_color = "#fef3c7"
            text_color = "#1f2937"
            secondary_color = "#fde68a"
        else:  # professional
            bg_color = "#ffffff"
            text_color = "#111827"
            secondary_color = "#f9fafb"

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{brand} - {task}</title>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}

        body {{
            font-family: {font_family}, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            color: {text_color};
            background-color: {bg_color};
            line-height: 1.6;
        }}

        .container {{
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 20px;
        }}

        /* Hero Section */
        .hero {{
            background: linear-gradient(135deg, {primary_color} 0%, {self._darken_color(primary_color)} 100%);
            color: white;
            padding: 100px 20px;
            text-align: center;
        }}

        .hero h1 {{
            font-size: 3.5rem;
            margin-bottom: 20px;
            font-weight: 700;
        }}

        .hero p {{
            font-size: 1.25rem;
            margin-bottom: 30px;
            opacity: 0.9;
        }}

        .cta-button {{
            display: inline-block;
            padding: 15px 40px;
            background: white;
            color: {primary_color};
            text-decoration: none;
            border-radius: 5px;
            font-weight: 600;
            font-size: 1.1rem;
            transition: transform 0.2s;
        }}

        .cta-button:hover {{
            transform: translateY(-2px);
        }}

        /* Features Section */
        .features {{
            padding: 80px 20px;
            background: {secondary_color};
        }}

        .features h2 {{
            text-align: center;
            font-size: 2.5rem;
            margin-bottom: 50px;
            color: {text_color};
        }}

        .features-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 30px;
        }}

        .feature-card {{
            background: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}

        .feature-card h3 {{
            color: {primary_color};
            margin-bottom: 15px;
            font-size: 1.5rem;
        }}

        /* Testimonials */
        .testimonials {{
            padding: 80px 20px;
            background: white;
        }}

        .testimonials h2 {{
            text-align: center;
            font-size: 2.5rem;
            margin-bottom: 50px;
        }}

        .testimonial-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 30px;
        }}

        .testimonial {{
            padding: 30px;
            background: {secondary_color};
            border-radius: 8px;
            border-left: 4px solid {primary_color};
        }}

        .testimonial-text {{
            font-style: italic;
            margin-bottom: 15px;
        }}

        .testimonial-author {{
            font-weight: 600;
            color: {primary_color};
        }}

        /* Footer */
        footer {{
            background: {text_color};
            color: white;
            padding: 40px 20px;
            text-align: center;
        }}

        footer p {{
            opacity: 0.8;
        }}

        /* Responsive */
        @media (max-width: 768px) {{
            .hero h1 {{
                font-size: 2.5rem;
            }}

            .features-grid,
            .testimonial-grid {{
                grid-template-columns: 1fr;
            }}
        }}
    </style>
</head>
<body>
    <!-- Hero Section -->
    <section class="hero">
        <div class="container">
            <h1>{brand}</h1>
            <p>{task}</p>
            <a href="#features" class="cta-button">Get Started</a>
        </div>
    </section>

    <!-- Features Section -->
    <section class="features" id="features">
        <div class="container">
            <h2>Why Choose {brand}?</h2>
            <div class="features-grid">
                <div class="feature-card">
                    <h3>Feature One</h3>
                    <p>Description of the first key feature that sets {brand} apart.</p>
                </div>
                <div class="feature-card">
                    <h3>Feature Two</h3>
                    <p>Description of the second key feature that provides value.</p>
                </div>
                <div class="feature-card">
                    <h3>Feature Three</h3>
                    <p>Description of the third key feature that completes the offering.</p>
                </div>
            </div>
        </div>
    </section>

    <!-- Testimonials -->
    <section class="testimonials">
        <div class="container">
            <h2>What People Say</h2>
            <div class="testimonial-grid">
                <div class="testimonial">
                    <p class="testimonial-text">"{brand} has transformed how we work. Highly recommended!"</p>
                    <p class="testimonial-author">— Customer One</p>
                </div>
                <div class="testimonial">
                    <p class="testimonial-text">"The best solution we've found. Exceeded our expectations."</p>
                    <p class="testimonial-author">— Customer Two</p>
                </div>
                <div class="testimonial">
                    <p class="testimonial-text">"Outstanding quality and service. Couldn't be happier."</p>
                    <p class="testimonial-author">— Customer Three</p>
                </div>
            </div>
        </div>
    </section>

    <!-- Footer -->
    <footer>
        <div class="container">
            <p>&copy; 2025 {brand}. All rights reserved.</p>
        </div>
    </footer>
</body>
</html>"""

        return html

    def _darken_color(self, hex_color: str) -> str:
        """Darken a hex color by 20%."""
        # Simple darkening - convert hex to RGB, reduce, convert back
        hex_color = hex_color.lstrip("#")
        r, g, b = int(hex_color[0:2], 16), int(hex_color[2:4], 16), int(hex_color[4:6], 16)
        r, g, b = max(0, int(r * 0.8)), max(0, int(g * 0.8)), max(0, int(b * 0.8))
        return f"#{r:02x}{g:02x}{b:02x}"
