# Auto-generated by multi-agent pipeline. Edit with care.

"""
Screenshot Agent - Generates PNG screenshots of HTML pages.
"""

import base64
from pathlib import Path
from typing import Any

from src.core.base import BaseFunctionalAgent
from src.core.types import AgentMetadata, AgentOutput, Artifact


class ScreenshotAgent(BaseFunctionalAgent):
    """
    Generates PNG screenshots of HTML pages.

    Uses headless browser (playwright/selenium) or fallback to HTML-to-image conversion.
    """

    def process(self, task: str, context: dict[str, Any]) -> dict[str, Any]:
        """
        Generate screenshot of HTML page.

        Args:
            task: Description of what to screenshot (may contain HTML path)
            context: Additional context including:
                - html_path: Path to HTML file (relative to project root or absolute)
                - run_id: Current run ID for output directory
                - width: Screenshot width (default: 1920)
                - height: Screenshot height (default: 1080)
        """
        html_path = context.get("html_path", "src/index.html")
        run_id = context.get("run_id", "latest")
        width = context.get("width", 1920)
        height = context.get("height", 1080)

        # Extract HTML path from task if provided
        if "src/" in task or "index.html" in task:
            import re

            match = re.search(r"(src/[\w/]+\.html|[\w/]+\.html)", task)
            if match:
                html_path = match.group(1)

        # Output directory - use absolute path to avoid Windows issues
        project_root = Path.cwd()
        output_dir = project_root / "out" / run_id / "Screenshot"
        output_dir.mkdir(parents=True, exist_ok=True)

        screenshot_path = output_dir / "preview.png"

        # Try to find HTML file
        html_file = None
        possible_locations = [
            Path(html_path),  # Absolute or relative to cwd
            Path("out") / run_id / html_path,  # In run output
            Path("out") / "latest" / html_path,  # Latest run
            Path("src") / html_path,  # In src/
        ]

        for loc in possible_locations:
            if loc.exists() and loc.is_file():
                html_file = loc
                break

        if not html_file:
            # Create placeholder screenshot
            self._create_placeholder_screenshot(screenshot_path, task, html_path)
            content = f"""# Screenshot Generated (Placeholder)

**Screenshot**: `{screenshot_path.relative_to(Path.cwd())}`
**Status**: Placeholder (HTML file not found at {html_path})

## Note

HTML file not found. Created placeholder screenshot.
To generate real screenshot, ensure HTML file exists and install:
- playwright: `pip install playwright && playwright install chromium`
- Or selenium: `pip install selenium`

## HTML Locations Checked

{chr(10).join(f"- {loc}" for loc in possible_locations)}
"""
        else:
            # Try to generate real screenshot
            screenshot_generated = False

            # Try playwright first
            try:
                from playwright.sync_api import sync_playwright

                screenshot_generated = self._screenshot_with_playwright(
                    html_file, screenshot_path, width, height
                )
            except ImportError:
                pass

            # Fallback to selenium
            if not screenshot_generated:
                try:
                    from selenium import webdriver
                    from selenium.webdriver.chrome.options import Options

                    screenshot_generated = self._screenshot_with_selenium(
                        html_file, screenshot_path, width, height
                    )
                except ImportError:
                    pass

            # Fallback to placeholder
            if not screenshot_generated:
                self._create_placeholder_screenshot(screenshot_path, task, str(html_file))

            # Safe relative path conversion
            project_root = Path.cwd()
            try:
                screenshot_rel = screenshot_path.relative_to(project_root)
            except Exception:
                screenshot_rel = str(screenshot_path)

            try:
                html_rel = html_file.relative_to(project_root) if html_file else html_path
            except Exception:
                html_rel = str(html_file) if html_file else html_path

            content = f"""# Screenshot Generated

**Screenshot**: `{screenshot_rel}`
**Source HTML**: `{html_rel}`
**Dimensions**: {width}x{height}
**Status**: {"Real screenshot" if screenshot_generated else "Placeholder (install playwright/selenium)"}

## Usage

Include this screenshot in your ZIP package or documentation.

## Installation (for real screenshots)

```bash
# Option 1: Playwright (recommended)
pip install playwright
playwright install chromium

# Option 2: Selenium
pip install selenium
# Requires ChromeDriver
```
"""

        # Read screenshot bytes
        screenshot_bytes = screenshot_path.read_bytes() if screenshot_path.exists() else b""

        artifacts = [
            Artifact(
                name="preview.png",
                type="image",
                content=screenshot_bytes,
                description="Screenshot preview of HTML page",
            )
        ]

        metadata = AgentMetadata(
            agent_name="ScreenshotAgent",
            stage="screenshots",
            input_summary=f"Screenshot of {html_path}",
        )

        return AgentOutput(content=content, artifacts=artifacts, metadata=metadata)

    def _screenshot_with_playwright(
        self, html_file: Path, output_path: Path, width: int, height: int
    ) -> bool:
        """Generate screenshot using Playwright."""
        try:
            from playwright.sync_api import sync_playwright

            # Ensure absolute paths
            html_abs = html_file.resolve() if html_file else None
            output_abs = output_path.resolve()

            if not html_abs or not html_abs.exists():
                return False

            with sync_playwright() as p:
                browser = p.chromium.launch(headless=True)
                page = browser.new_page(viewport={"width": width, "height": height})

                # Load HTML file using file:// URL
                file_url = f"file:///{str(html_abs).replace(chr(92), '/')}"  # Windows path fix
                page.goto(file_url, wait_until="networkidle", timeout=30000)

                # Take screenshot
                page.screenshot(path=str(output_abs), full_page=True)
                browser.close()

            return True
        except Exception:
            # Log error but don't fail - will use placeholder
            return False

    def _screenshot_with_selenium(
        self, html_file: Path, output_path: Path, width: int, height: int
    ) -> bool:
        """Generate screenshot using Selenium."""
        try:
            from selenium import webdriver
            from selenium.webdriver.chrome.options import Options

            options = Options()
            options.add_argument("--headless")
            options.add_argument("--no-sandbox")
            options.add_argument(f"--window-size={width},{height}")

            driver = webdriver.Chrome(options=options)
            driver.get(f"file://{html_file.absolute()}")
            driver.save_screenshot(str(output_path))
            driver.quit()

            return True
        except Exception:
            return False

    def _create_placeholder_screenshot(self, output_path: Path, task: str, html_path: str):
        """Create a placeholder PNG image."""
        try:
            from PIL import Image, ImageDraw, ImageFont

            # Create image
            img = Image.new("RGB", (1920, 1080), color="#f0f0f0")
            draw = ImageDraw.Draw(img)

            # Try to use a font
            try:
                font_large = ImageFont.truetype("arial.ttf", 48)
                font_small = ImageFont.truetype("arial.ttf", 24)
            except:
                font_large = ImageFont.load_default()
                font_small = ImageFont.load_default()

            # Draw text
            text = f"Screenshot Placeholder\n\nTask: {task}\nHTML: {html_path}\n\nInstall playwright or selenium for real screenshots"
            draw.text((100, 100), text, fill="#333", font=font_large)

            img.save(output_path, "PNG")
        except ImportError:
            # Fallback: create minimal PNG
            # PNG header + minimal valid PNG
            png_data = base64.b64decode(
                "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=="
            )
            output_path.write_bytes(png_data)
