# Auto-generated by multi-agent pipeline. Edit with care.

"""
ZIP Packager Agent - Creates a distributable ZIP package from artifacts.
"""

import zipfile
from pathlib import Path
from typing import Any

from src.core.base import BaseFunctionalAgent
from src.core.types import AgentMetadata, AgentOutput, Artifact


class ZipPackagerAgent(BaseFunctionalAgent):
    """
    Packages multiple artifacts into a single ZIP file.

    Inputs: List of artifact paths (relative to project root)
    Output: A ZIP file containing all artifacts
    """

    def process(self, task: str, context: dict[str, Any]) -> dict[str, Any]:
        """
        Create a ZIP package from input artifacts.

        Args:
            task: Description of what to package
            context: Additional context including:
                - artifacts: List of artifact paths (relative to project root)
                - run_id: Current run ID for output directory
        """
        run_id = context.get("run_id", "latest")

        # Collect artifacts from previous stages in memory
        artifacts = []

        # Look for artifacts in context (from previous stages)
        for key, value in context.items():
            if key.endswith(".artifacts") and isinstance(value, list):
                for art in value:
                    if isinstance(art, dict):
                        art_path = art.get("name") or art.get("path", "")
                        if art_path:
                            artifacts.append(art_path)
                    elif isinstance(art, str):
                        artifacts.append(art)

        # Also try to extract from task if it contains file paths
        if not artifacts:
            import re

            paths = re.findall(r"[\w/]+\.(?:html|md|txt|png)", task)
            if paths:
                artifacts = paths

        # Default artifacts if nothing found
        if not artifacts:
            # Common artifact locations based on typical pipeline structure
            artifacts = [
                "src/index.html",
                "README.md",
                "reports/lint_report.md",
                "reports/a11y_report.md",
                "screenshots/preview.png",
            ]

        # Output directory
        output_dir = Path("out") / run_id / "Package ZIP"
        output_dir.mkdir(parents=True, exist_ok=True)

        zip_path = output_dir / "package.zip"

        # Create ZIP file
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zipf:
            # Add each artifact if it exists
            added_files = []
            project_root = Path.cwd()

            for artifact_path in artifacts:
                artifact_file = Path(artifact_path)

                # Try to find artifact in various locations
                possible_locations = [
                    project_root / artifact_file,  # Absolute or relative to cwd
                    project_root
                    / "out"
                    / run_id
                    / "code_skeleton"
                    / artifact_file.name,  # Code skeleton stage
                    project_root
                    / "out"
                    / run_id
                    / "Documentation"
                    / artifact_file.name,  # Documentation stage
                    project_root
                    / "out"
                    / run_id
                    / "Static Lint"
                    / artifact_file.name,  # Lint stage
                    project_root
                    / "out"
                    / run_id
                    / "Accessibility Audit"
                    / artifact_file.name,  # A11y stage
                    project_root
                    / "out"
                    / run_id
                    / "Screenshot"
                    / artifact_file.name,  # Screenshot stage
                    project_root / "out" / run_id / artifact_file,  # Direct in run output
                    project_root / "out" / "latest" / artifact_file,  # Latest run
                    project_root / artifact_file.name,  # Just filename in cwd
                ]

                found = False
                for loc in possible_locations:
                    if loc.exists() and loc.is_file():
                        # Add to ZIP with relative path
                        arcname = (
                            artifact_file.name
                            if "/" not in str(artifact_file)
                            else str(artifact_file)
                        )
                        zipf.write(loc, arcname=arcname)
                        added_files.append(str(loc))
                        found = True
                        break

                if not found:
                    # Create placeholder file
                    placeholder = output_dir / artifact_file.name
                    placeholder.write_text(
                        f"# Placeholder for {artifact_path}\n\nFile not found during packaging."
                    )
                    zipf.write(placeholder, arcname=artifact_file.name)
                    added_files.append(f"{artifact_path} (placeholder)")

            # Add a manifest file
            manifest_content = f"""# Package Manifest

Generated: {run_id}
Task: {task}

Files included:
{chr(10).join(f"- {f}" for f in added_files)}

Total files: {len(added_files)}
"""
            manifest_path = output_dir / "MANIFEST.txt"
            manifest_path.write_text(manifest_content)
            zipf.write(manifest_path, arcname="MANIFEST.txt")

        # Generate summary
        zip_size = zip_path.stat().st_size
        content = f"""# Package Created Successfully

**ZIP File**: `{zip_path.relative_to(Path.cwd())}`
**Size**: {zip_size:,} bytes ({zip_size / 1024:.1f} KB)
**Files**: {len(added_files) + 1} (including manifest)

## Contents

{chr(10).join(f"- {f}" for f in added_files)}
- MANIFEST.txt

## Usage

Extract the ZIP file to get all artifacts:

```bash
unzip {zip_path.name} -d extracted/
```

Or use Python:

```python
import zipfile
with zipfile.ZipFile("{zip_path.name}", "r") as zipf:
    zipf.extractall("extracted/")
```
"""

        artifacts = [
            Artifact(
                name="package.zip",
                type="binary",
                content=zip_path.read_bytes() if zip_path.exists() else b"",
                description="Distributable package ZIP",
            ),
            Artifact(
                name="MANIFEST.txt",
                type="text",
                content=manifest_content,
                description="Package manifest",
            ),
        ]

        metadata = AgentMetadata(
            agent_name="ZipPackagerAgent",
            stage="packaging",
            input_summary=f"Packaged {len(added_files)} files",
        )

        return AgentOutput(content=content, artifacts=artifacts, metadata=metadata)
